### ISSUE TITLE
XL Release 8.0.2

### ISSUE THREAD

**Issue by Darryn-George** [xebialabs-community/xlr-ispw-plugin#15]
Hi,

Does this plugin work for XL Release 8.0.2 and CES 18.3.2?

Can't connect to Ispw Services: Server.
Exception: HTTP response code 401 (Unauthorized)

I am receiving the below error, and the Personal Access Token used is correct...

Regards
Darryn

**Comment by jdewinne** [comment]
Have you tried making the REST call using a tool like [postman](https://www.getpostman.com/)? You could use the following url:
`[your_ispw_url]/compuware/ws/Config/version`
And use the following for the authorization header: `Authorization: [your_ces_token]`

Does that result in the same 401 or a different message?

**Comment by Darryn-George** [comment]
Hi,

I managed to get it working, the URL configured in the XL Release Shared configuration should be "http://host.name:48226"...

I can now retrieve information from ISPW such as assignment information from a task, but the test connection in XL Release Shared configuration still throws a 401 error, looks like this function don't work.

Thanks again for all your assistance.

Regards
Darryn
