### ISSUE TITLE
Incompatibility with XLR 7.0.0

### ISSUE THREAD

**Issue by vlussenburg** [xebialabs-community/xlr-ispw-plugin#3]
Widgets do not render correctly.
![image001](https://user-images.githubusercontent.com/726645/27089914-fa50e924-5018-11e7-8187-cf9d3229c029.png)

**Comment by jdewinne** [comment]
Fixed by @Hes-Siemelink 
See [v3.0.4](https://github.com/xebialabs-community/xlr-ispw-plugin/releases)
